### ISSUE TITLE
ipad pro 2024 触摸屏无法控制光标

### ISSUE THREAD

**Issue by crazyshitass** [TrueZhuangJia/moonlight-ios#1]
如题，多指可以触发键盘，但是光标完全无法控制，已经是“native multi-point touch”模式

**Comment by crazyshitass** [comment]
ios也一样的问题，ios17.5.1

**Comment by TrueZhuangJia** [comment]
> 如题，多指可以触发键盘，但是光标完全无法控制，已经是“native multi-point touch”模式

你可能是指键盘触发后可能会盖住远程的光标, 这是因为sunshine和moonlight之间是没有机制判断，远程光标位置在哪里的。
针对这点我刚好有在做优化。代码已经提交， 明天整个测试包。

**Comment by crazyshitass** [comment]
> > 如题，多指可以触发键盘，但是光标完全无法控制，已经是“native multi-point touch”模式
> 
> 你可能是指键盘触发后可能会盖住远程的光标, 这是因为sunshine和moonlight之间是没有机制判断，远程光标位置在哪里的。 针对这点我刚好有在做优化。代码已经提交， 明天整个测试包。

感谢大佬付出：）

**Comment by TrueZhuangJia** [comment]
> ios也一样的问题，ios17.5.1

如果你同时反映了安卓版的类似问题， 建议先安装一个有悬浮键盘的输入法， 我记得搜狗就还行。 我是因为iOS悬浮建盘太烂，尺寸太小才去优化的。

**Comment by TrueZhuangJia** [comment]
> > > 如题，多指可以触发键盘，但是光标完全无法控制，已经是“native multi-point touch”模式
> > 
> > 
> > 你可能是指键盘触发后可能会盖住远程的光标, 这是因为sunshine和moonlight之间是没有机制判断，远程光标位置在哪里的。 针对这点我刚好有在做优化。代码已经提交， 明天整个测试包。
> 
> 感谢大佬付出：）

请到release页面下载临时版本。没有sideloadly的话等明天的altstore包

**Comment by crazyshitass** [comment]
> > > > 如题，多指可以触发键盘，但是光标完全无法控制，已经是“native multi-point touch”模式
> > > 
> > > 
> > > 你可能是指键盘触发后可能会盖住远程的光标, 这是因为sunshine和moonlight之间是没有机制判断，远程光标位置在哪里的。 针对这点我刚好有在做优化。代码已经提交， 明天整个测试包。
> > 
> > 
> > 感谢大佬付出：）
> 
> 请到release页面下载临时版本。没有sideloadly的话等明天的altstore包

收到，感谢及时改进！

**Comment by crazyshitass** [comment]
用了最新的版本，还是一样的问题，多点触控无法操作页面……[20240526V902-moonlight-iOS-ZWM-AltStore.ipa](https://github.com/TrueZhuangJia/moonlight-ios-NativeMultiTouchPassthrough/releases/download/betterGestureRecognizer/20240526V902-moonlight-iOS-ZWM-AltStore.ipa)

**Comment by TrueZhuangJia** [comment]
> 用了最新的版本，还是一样的问题，多点触控无法操作页面……[20240526V902-moonlight-iOS-ZWM-AltStore.ipa](https://github.com/TrueZhuangJia/moonlight-ios-NativeMultiTouchPassthrough/releases/download/betterGestureRecognizer/20240526V902-moonlight-iOS-ZWM-AltStore.ipa)

新功能的图片和动图操作说明看了吗？按说明操作不能解决你的问题，那你提的和我做的不是一回事。
另外请先学会怎么反馈问题和需求，不要当一上来就"还是用不了" 连个描述都没有，这样和伸手党有什么区别？

**Comment by TrueZhuangJia** [comment]
> 用了最新的版本，还是一样的问题，多点触控无法操作页面……[20240526V902-moonlight-iOS-ZWM-AltStore.ipa](https://github.com/TrueZhuangJia/moonlight-ios-NativeMultiTouchPassthrough/releases/download/betterGestureRecognizer/20240526V902-moonlight-iOS-ZWM-AltStore.ipa)

![image](https://github.com/TrueZhuangJia/moonlight-ios-NativeMultiTouchPassthrough/assets/78474576/df046165-1a54-49b8-968d-a0a9737cf8ad)

**Comment by crazyshitass** [comment]
> > 用了最新的版本，还是一样的问题，多点触控无法操作页面……[20240526V902-moonlight-iOS-ZWM-AltStore.ipa](https://github.com/TrueZhuangJia/moonlight-ios-NativeMultiTouchPassthrough/releases/download/betterGestureRecognizer/20240526V902-moonlight-iOS-ZWM-AltStore.ipa)
> 
> 新功能的图片和动图操作说明看了吗？按说明操作不能解决你的问题，那你提的和我做的不是一回事。 另外请先学会怎么反馈问题和需求，不要当一上来就"还是用不了" 连个描述都没有，这样和伸手党有什么区别？

抱歉，是我表述问题。目前遇到的情况是：1、原版moonlight可以控制光标，但是多点触控无法使用，比如双指翻页；2、安装最新版的ZWM-AltStore.ipa（包括老板的0517），无法控制光标，页面是锁定状态，无法点按，也就无从谈起多点触控操作。

**Comment by TrueZhuangJia** [comment]
> > > 用了最新的版本，还是一样的问题，多点触控无法操作页面……[20240526V902-moonlight-iOS-ZWM-AltStore.ipa](https://github.com/TrueZhuangJia/moonlight-ios-NativeMultiTouchPassthrough/releases/download/betterGestureRecognizer/20240526V902-moonlight-iOS-ZWM-AltStore.ipa)
> > 
> > 
> > 新功能的图片和动图操作说明看了吗？按说明操作不能解决你的问题，那你提的和我做的不是一回事。 另外请先学会怎么反馈问题和需求，不要当一上来就"还是用不了" 连个描述都没有，这样和伸手党有什么区别？
> 
> 抱歉，是我表述问题。目前遇到的情况是：1、原版moonlight可以控制光标，但是多点触控无法使用，比如双指翻页；2、安装最新版的ZWM-AltStore.ipa（包括老板的0517），无法控制光标，页面是锁定状态，无法点按，也就无从谈起多点触控操作。

看完你的描述 我认为你提的问题是对Windows系统触屏操作不习惯不熟悉造成的。 我的多点触控moonlight作用就是按Sunshine要求把本地触点信息透传给远程PC， Sunshine会再把触点的坐标、压力值等信息透传给Windows，也就是说和操作Windows平板的方式一样的。
你提的那些 在多点触控模式下都有自己操作方式， 和你在手机上操作其实差不多。 比如文字输入光标就是手指点在那里就跟到哪里，  二指翻页啥的根本就不需要 因为多数页面是可以像手机浏览一样上下划动。
总之不会的话再去学习一下。

**Comment by crazyshitass** [comment]
> > > > 用了最新的版本，还是一样的问题，多点触控无法操作页面……[20240526V902-moonlight-iOS-ZWM-AltStore.ipa](https://github.com/TrueZhuangJia/moonlight-ios-NativeMultiTouchPassthrough/releases/download/betterGestureRecognizer/20240526V902-moonlight-iOS-ZWM-AltStore.ipa)
> > > 
> > > 
> > > 新功能的图片和动图操作说明看了吗？按说明操作不能解决你的问题，那你提的和我做的不是一回事。 另外请先学会怎么反馈问题和需求，不要当一上来就"还是用不了" 连个描述都没有，这样和伸手党有什么区别？
> > 
> > 
> > 抱歉，是我表述问题。目前遇到的情况是：1、原版moonlight可以控制光标，但是多点触控无法使用，比如双指翻页；2、安装最新版的ZWM-AltStore.ipa（包括老板的0517），无法控制光标，页面是锁定状态，无法点按，也就无从谈起多点触控操作。
> 
> 看完你的描述 我认为你提的问题是对Windows系统触屏操作不习惯不熟悉造成的。 我的多点触控moonlight作用就是按Sunshine要求把本地触点信息透传给远程PC， Sunshine会再把触点的坐标、压力值等信息透传给Windows，也就是说和操作Windows平板的方式一样的。 你提的那些 在多点触控模式下都有自己操作方式， 和你在手机上操作其实差不多。 比如文字输入光标就是手指点在那里就跟到哪里， 二指翻页啥的根本就不需要 因为多数页面是可以像手机浏览一样上下划动。 总之不会的话再去学习一下。

我是在macos上用sunshine，不知道是不是宿主机的系统因素影响了效果。因为macos在原版的moonlight下，是可以直接控制光标的，点击操作也都是正常的。

**Comment by TrueZhuangJia** [comment]
害， 你小子， 会不会反馈问题。。不早说是macOS。
你先用我的moonlight android试一下macOS效果吧。 判断过去，大概mac版sunshine根本不支持多点触控， 点都点不动。

**Comment by crazyshitass** [comment]
> 害， 你小子， 会不会反馈问题。。不早说是macOS。 你先用我的moonlight android试一下macOS效果吧。 判断过去，大概mac版sunshine根本不支持多点触控， 点都点不动。

抱歉抱歉，前面没考虑宿主机系统会影响客户端的操作

**Comment by TrueZhuangJia** [comment]
> > 害， 你小子， 会不会反馈问题。。不早说是macOS。 你先用我的moonlight android试一下macOS效果吧。 判断过去，大概mac版sunshine根本不支持多点触控， 点都点不动。
> 
> 抱歉抱歉，前面没考虑宿主机系统会影响客户端的操作

老铁， 破案了， macOS根本就没有触摸屏支持， 所以不会有多点触控驱动和机制的。
 
![image](https://github.com/TrueZhuangJia/moonlight-ios-NativeMultiTouchPassthrough/assets/78474576/0c542cdb-c2b9-4108-b914-7754a3a06622)

我已经 把官方版的单点触屏模式恢复了，需要的话自取。

**Comment by TrueZhuangJia** [comment]
关闭
