### ISSUE TITLE
Multi Touch (Native) Doesn’t Work

### ISSUE THREAD

**Issue by alany08** [TrueZhuangJia/moonlight-ios#11]
Genshin: Selecting native multi touch simply doesn’t do anything, can’t click.

**Comment by alany08** [comment]
I am running with cmdline args to make it think it’s running on genshin cloud server

**Comment by TrueZhuangJia** [comment]
Guess you're running shield (no multi-touch support) instead of sunshine?

**Comment by TrueZhuangJia** [comment]
turn off Nvidia shield, and install sunshine
https://github.com/LizardByte/Sunshine/releases/tag/v0.23.1
