### ISSUE TITLE
能否添加对apple pencil的捏和双击的支持并映射成快捷键

### ISSUE THREAD

**Issue by cainiao524** [TrueZhuangJia/moonlight-ios#15]
差一点就可以完全拿ipad当副屏画画了

**Comment by NalCol** [comment]
#16 你的Apple Pencil在软件上不会出bug吗？看看我这个issue😂

**Comment by TrueZhuangJia** [comment]
相关操作不能通过键盘和鼠标实现吗？ 可以的话就能添加按键

**Comment by cainiao524** [comment]
差不多就是能比如双击=键盘按e切橡皮，捏=ctrl+z组合键这样。不知道Windows自己有没有关于触控笔自带按键输入的识别

**Comment by TrueZhuangJia** [comment]
> 差不多就是能比如双击=键盘按e切橡皮，捏=ctrl+z组合键这样。不知道Windows自己有没有关于触控笔自带按键输入的识别

组合键，键盘本来就可以添加。 可以添加为屏显按键，或者从右边缘向内滑动打开的菜单命令。
设置菜单里切换到自定义屏显手柄， 串流的时候打开布局工具， 点加号就可以添加。
[How.to.add.keyboard.command.for.moonlight-iOS](https://b23.tv/fgdRJk8)

**Comment by cainiao524** [comment]
不能直接识别苹果笔按键触发组合键吗

**Comment by TrueZhuangJia** [comment]
> 不能直接识别苹果笔按键触发组合键吗

你是说笔按到屏显按键上没反应，还是啥意思

**Comment by lootcouncil** [comment]
> > Can't you directly identify the Apple Pencil keystrokes to trigger the key combination?
> 
> Are you saying that the pen doesn't respond when it is pressed on the on-screen button, or what?

I think we're talking about adding support for both the squeeze and double-tap events from an apple pencil pro.  
![Screenshot 2024-09-23 052327](https://github.com/user-attachments/assets/f5ee518b-8772-40a6-8f0a-a3114dbede4a)
![Screenshot 2024-09-23 052351](https://github.com/user-attachments/assets/4a7011d2-d1e9-43c5-9124-274ef3c3ec5d)

Whenever we double-tap on the pencil, we can send a keyboard shortcut or whenever we squeeze, that could be the equivalent to pressing down the middle-mouse button or something similar.

Regardless, wanted to thank you for this fork.

**Comment by TrueZhuangJia** [comment]
> > > Can't you directly identify the Apple Pencil keystrokes to trigger the key combination?
> > 
> > 
> > Are you saying that the pen doesn't respond when it is pressed on the on-screen button, or what?
> 
> I think we're talking about adding support for both the squeeze and double-tap events from an apple pencil pro. ![Screenshot 2024-09-23 052327](https://private-user-images.githubusercontent.com/933670/369870261-f5ee518b-8772-40a6-8f0a-a3114dbede4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwOTU2MjAsIm5iZiI6MTcyNzA5NTMyMCwicGF0aCI6Ii85MzM2NzAvMzY5ODcwMjYxLWY1ZWU1MThiLTg3NzItNDBhNi04ZjBhLWEzMTE0ZGJlZGU0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QxMjQyMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MWNjYjI1ODc3YjVjZmZmMmU5YjgwMGU3N2U3MmEzOTE1ODIzYzhkYzcyMTlhNWFkOGFiM2VkZGVmNThkZjA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uoXFjTNPUR7HzYn9szX9wV2VKqkZduFt68qiMS5vstg) ![Screenshot 2024-09-23 052351](https://private-user-images.githubusercontent.com/933670/369870288-4a7011d2-d1e9-43c5-9124-274ef3c3ec5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwOTU2MjAsIm5iZiI6MTcyNzA5NTMyMCwicGF0aCI6Ii85MzM2NzAvMzY5ODcwMjg4LTRhNzAxMWQyLWQxZTktNDNjNS05MTI0LTI3NGVmM2MzZWM1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QxMjQyMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODVmMGE0MmRiMTMwNGVkNGIyOTg3OWI3ODYyZTJkMTFiNzgzNWU2NTI5MjFkOWExNGViNDExMWJhZTNjOWRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3ZYcQOdm08JbmNdgVY1TJr-HSbcnZKySEQbGSfpaq7U)
> 
> Whenever we double-tap on the pencil, we can send a keyboard shortcut or whenever we squeeze, that could be the equivalent to pressing down the middle-mouse button or something similar.
> 
> Regardless, wanted to thank you for this fork.

Nope, not going to implement this, at least for the foreseeable future
I'm not a user of apple pencil. I suggest to add custom on-screen keyboard buttons instead.

**Comment by TrueZhuangJia** [comment]
came back to this issue to tell you guys, this feature is about to be available in maybe a few days, or 2 weeks

**Comment by TrueZhuangJia** [comment]
Pencil Pro Pack has been release with VoidLink 3.3.0 update as an in-app-purchase. Check it out on App Store:
https://apps.apple.com/app/voidlink-extreme/id6755103808
