### ISSUE TITLE
正确处理 Apple Pencil 抬起 // Handle Apple Pencil lift up correctly

### ISSUE THREAD

**Issue by NalCol** [TrueZhuangJia/moonlight-ios#16]
**Bug 描述 // Describe the bug**
在某些软件上压感笔抬起笔时没有检测到
会导致”连笔“（上一个笔迹末端连到下一个笔迹始端）
这个issue在原版moonlight-ios上有了一段时间了
[moonlight-ios #638](https://github.com/moonlight-stream/moonlight-ios/issues/638)

**复现步骤 // Steps to reproduce**
1. 找只 Apple Pencil
2. 输入模式调成”多点触控“
3. 在受影响的应用写字（比如 Classin）

**设备信息 // Device details**
 - iOS version: iPadOS 17.0
 - Device model: iPad Pro 2021 (M1)

**主机信息 // Server PC details**
 - OS: Windows 11 22H2
 - Sunshine 0.21.2

**Comment by TrueZhuangJia** [comment]
我没有apple pencil, 所以没法复现并解决这个问题,，也不理解你提出的新需求
不过其他用apple pencil的用户并没有反馈类似情况， 因此我一直以为对apple pencil的支持比较完善的

**Comment by NalCol** [comment]
> 我没有apple pencil, 所以没法复现并解决这个问题,，也不理解你提出的新需求 不过其他用apple pencil的用户并没有反馈类似情况， 因此我一直以为对apple pencil的支持比较完善的

这玩意没法正常处理笔抬起的状态，在某些软件上会表现出你笔没抬起来。
主要是iPad能替代数位板的功能，无线的数位板啊！老爽了。。
