### ISSUE TITLE
是否可以新增触摸板模式下.双点屏幕右键.双击单点后的拖拽功能.自己屏幕自适应缩放鼠标拖动？

### ISSUE THREAD

**Issue by DancingDolphins** [TrueZhuangJia/moonlight-ios#17]
如下vnc viewer之功能？
https://github.com/user-attachments/assets/f289cf25-d945-478a-8003-ced4f1b80cc7

以下操作模式可参考![image](https://github.com/user-attachments/assets/ce79a033-ac9e-449b-8c66-0322a44399f4)

**Comment by TrueZhuangJia** [comment]
双指屏幕右键, 双击拖动已经实现了。
其他的不会去做。

由于审核原因， app store版暂时无法更新， 安装Readme首页上的TestFlight版本才有上述功能

**Comment by DancingDolphins** [comment]
谢谢恩泽.
还有一个双指拖动滚动条.也是需求点.其他的确可有可无.

**Comment by DancingDolphins** [comment]
> 谢谢恩泽.
> 还有一个双指拖动滚动条.也是需求点.其他的确可有可无.

经测试.已经实现
