### ISSUE TITLE
Random stutter when scrolling or dragging windows with native touch

### ISSUE THREAD

**Issue by r33f3r** [TrueZhuangJia/moonlight-ios#18]
Intermittent issue while using native touch. The stream is unaffected (no increased latency or dropped frames) but there is lag/stutter while scrolling or dragging windows. All background processes are unaffected, i.e. video/audio playback continues as usual. This doesn't happen all the time, it's at random intervals. Sometimes it happens more frequently than other times. Maybe an issue with Windows touch recognition or the touch passthrough?

iPad Pro 11 2018, 11 inch
iPadOS 18

 Windows 11 Home 23H2
 RTX 4080
 Nvidia GPU driver: 561.09

**Comment by TrueZhuangJia** [comment]
Turn off AirDrop, AirPlay & Handoff
or
Switch your PC wired Ethernet adaptor to force 100mbps mode

Mind your bit rate settings, do not exceed network bandwidth.
