### ISSUE TITLE
希望添加更高码率的选项

### ISSUE THREAD

**Issue by netsflex** [TrueZhuangJia/moonlight-ios#2]
如标题所述，Moonlight官方支持的码率最高只有150mbps，且在120hz HDR等高画质条件下串流时，更高码率可以明显提高图像质量。可以参考阿西西的实现，他将码率开放到了300mbps

**Comment by TrueZhuangJia** [comment]
> 如标题所述，Moonlight官方支持的码率最高只有150mbps，且在120hz HDR等高画质条件下串流时，更高码率可以明显提高图像质量。可以参考阿西西的实现，他将码率开放到了300mbps

这个功能我不会去加， 因为我自己是2K HDR 60fps, 50Mbps就够了。 我自己都把电脑端的有线网卡限制为100Mbp模式，视角转动效果更好。

如果更高码率效果明显的话， 建议可以先去调高Sunshine的视频编码配置， 也会有类似效果。
![image](https://github.com/TrueZhuangJia/moonlight-ios-NativeMultiTouchPassthrough/assets/78474576/91f85633-86c3-49f2-bfd0-95d3a9a22876)
![image](https://github.com/TrueZhuangJia/moonlight-ios-NativeMultiTouchPassthrough/assets/78474576/e29c6145-7f6a-4477-9ce8-5381df8ad913)

**Comment by netsflex** [comment]
好的

**Comment by TrueZhuangJia** [comment]
> 如标题所述，Moonlight官方支持的码率最高只有150mbps，且在120hz HDR等高画质条件下串流时，更高码率可以明显提高图像质量。可以参考阿西西的实现，他将码率开放到了300mbps

试了一下， 并不难， 就加上了。最高允许500Mbps。请到最新 release 下载页面

**Comment by TrueZhuangJia** [comment]
> 好的

试了一下， 并不难， 就加上了。最高允许500Mbps。请到最新 release 下载页面

> 如标题所述，Moonlight官方支持的码率最高只有150mbps，且在120hz HDR等高画质条件下串流时，更高码率可以明显提高图像质量。可以参考阿西西的实现，他将码率开放到了300mbps

试了一下， 并不难 就加上了。最高允许500Mbps。请到最新 release 页面下载。

**Comment by TrueZhuangJia** [comment]
已添加
