### ISSUE TITLE
Full screen on external monitor

### ISSUE THREAD

**Issue by phi1-h** [TrueZhuangJia/moonlight-ios#22]
Hi, can you please implement this PR?
https://github.com/moonlight-stream/moonlight-ios/pull/608

**Comment by TrueZhuangJia** [comment]
not planned. And here's another excuse: I have no device (external display for my iPad) to debug & test

**Comment by ghost** [comment]
Yes please. 🙏

**Comment by TrueZhuangJia** [comment]
implemented on Testflight Build 82 (don't install the latest one)
thanks to @xzzpig

**Comment by sown0868** [comment]
Hi @TrueZhuangJia , can you share the IPA file for TestFlight Build 82? Thanks!
