### ISSUE TITLE
Rumble Support

### ISSUE THREAD

**Issue by nevespt** [TrueZhuangJia/moonlight-ios#23]
Can u add this?
https://github.com/moonlight-stream/moonlight-ios/pull/647

**Comment by TrueZhuangJia** [comment]
I'm not a game controller user number one.
number two, 阿西西的日常 AxixiTV is a son of bxtch, a thief who stole my idea to make his own video, ignoring all my credits.

**Comment by nevespt** [comment]
@TrueZhuangJia 
But can u add rumble support anyway for the people that use player one?

**Comment by viseniv** [comment]
I also want to have rumble, i never use the touch screen controls.

**Comment by twilightgod** [comment]
+1 would be great to see this feature as MFI controllers don’t support rumble in iOS
