### ISSUE TITLE
码率选项失效

### ISSUE THREAD

**Issue by ChrisKimZHT** [TrueZhuangJia/moonlight-ios#3]
Moonlight 中的码率选项失效，无论怎么选都是 50Mbps 码率，导致在低带宽情况下卡死。原版 Moonlight 无此问题。

Sunshine: v0.23.1
Moonlight: https://github.com/TrueZhuangJia/moonlight-ios-NativeMultiTouchPassthrough/releases/tag/betterGestureRecognizer

**Comment by TrueZhuangJia** [comment]
> Moonlight 中的码率选项失效，无论怎么选都是 50Mbps 码率，导致在低带宽情况下卡死。原版 Moonlight 无此问题。
> 
> Sunshine: v0.23.1 Moonlight: https://github.com/TrueZhuangJia/moonlight-ios-NativeMultiTouchPassthrough/releases/tag/betterGestureRecognizer

我没有到动码率相关的代码。我自己在iOS17.2 ipad mini6上也没有这个问题， 码率可以调到很最低并访问远程桌面，画质也相应降低。
滑不动那个码率slider可能是触摸的问题， 偶尔是会遇到的。建议对准了多拖动几次。如果问题不是我描述的这种情况，请提供更多 信息。

**Comment by ChrisKimZHT** [comment]
原版设置

![image](https://github.com/TrueZhuangJia/moonlight-ios-NativeMultiTouchPassthrough/assets/49368462/0776c8c8-a0ae-44f1-a552-dc5af6a7427a)

原版码率：

![image](https://github.com/TrueZhuangJia/moonlight-ios-NativeMultiTouchPassthrough/assets/49368462/a06d220e-fdf9-41d9-a88d-bba12a796f36)

修改版设置：

![image](https://github.com/TrueZhuangJia/moonlight-ios-NativeMultiTouchPassthrough/assets/49368462/2b36dd65-a30c-4dd7-8c60-d0194aa9d320)

修改版码率：

![image](https://github.com/TrueZhuangJia/moonlight-ios-NativeMultiTouchPassthrough/assets/49368462/3c294825-3831-4eab-8660-1566ea62de5b)

**Comment by TrueZhuangJia** [comment]
> 原版设置
> 
> ![image](https://private-user-images.githubusercontent.com/49368462/339630510-0776c8c8-a0ae-44f1-a552-dc5af6a7427a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMzk2ODAsIm5iZiI6MTcxODMzOTM4MCwicGF0aCI6Ii80OTM2ODQ2Mi8zMzk2MzA1MTAtMDc3NmM4YzgtYTBhZS00NGYxLWE1NTItZGM1YWY2YTc0MjdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA0Mjk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ZmJkMmRlNDgxZjU5OTY0MzAzOGFhZDVkODZjMzE0MTdhOGQzMTU3ZmZmMjY1YTcyN2NmNTcyMWEzMmQ4ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VMlm0Dh0CPSw4Nc2tFsNky_OPMHUwrtFWCQeVDuqfKA)
> 
> 原版码率：
> 
> ![image](https://private-user-images.githubusercontent.com/49368462/339630568-a06d220e-fdf9-41d9-a88d-bba12a796f36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMzk2ODAsIm5iZiI6MTcxODMzOTM4MCwicGF0aCI6Ii80OTM2ODQ2Mi8zMzk2MzA1NjgtYTA2ZDIyMGUtZmRmOS00MWQ5LWE4OGQtYmJhMTJhNzk2ZjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA0Mjk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3NzQwOTA5Yzk1YTI3MmRhMjQwZDkwMmM3MDJlYjc0YzE4MzNmNDkyZTY1ZTJkMzQ4ZTFjYjE3M2RmOTM5ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NOsercgOvyc1Vm6xi4aXk5fbJjxSiH_xnpCzggxr8iY)
> 
> 修改版设置：
> 
> ![image](https://private-user-images.githubusercontent.com/49368462/339630626-2b36dd65-a30c-4dd7-8c60-d0194aa9d320.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMzk2ODAsIm5iZiI6MTcxODMzOTM4MCwicGF0aCI6Ii80OTM2ODQ2Mi8zMzk2MzA2MjYtMmIzNmRkNjUtYTMwYy00ZGQ3LThjNjAtZDAxOTRhYTlkMzIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA0Mjk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmNzdhZTJkODg1ZDM1OGEyMmUyYmM3MDg0NGM2ZDQwMjgyNDU1ODBkOTEyYzRiM2FhYzk2MDc5NDFmNThkYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._rH6Jw5l2WhJRnf1C3TWrLb9OXuW3Ptu16lJG0Tmtdo)
> 
> 修改版码率：
> 
> ![image](https://private-user-images.githubusercontent.com/49368462/339630664-3c294825-3831-4eab-8660-1566ea62de5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMzk2ODAsIm5iZiI6MTcxODMzOTM4MCwicGF0aCI6Ii80OTM2ODQ2Mi8zMzk2MzA2NjQtM2MyOTQ4MjUtMzgzMS00ZWFiLTg2NjAtMTU2NmVhNjJkZTViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA0Mjk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMWM1MzcwNjhmODY1OWYzZjYyMGZiZmVkYjQyYzRhZWFiMjhhODdhMWViODcwMTQ4MGM3Y2FmZThmZjE0ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yfsk7M2aRO29cOqpWNsdnT3RZ1jPw5cTqXDsvpAd9ho)

你是iphone还是ipad?
方便的话，给我邮箱veimin@foxmail.com发个wx号什么的， 我加你私聊。

**Comment by TrueZhuangJia** [comment]
> 原版设置
> 
> ![image](https://private-user-images.githubusercontent.com/49368462/339630510-0776c8c8-a0ae-44f1-a552-dc5af6a7427a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNDE5NzUsIm5iZiI6MTcxODM0MTY3NSwicGF0aCI6Ii80OTM2ODQ2Mi8zMzk2MzA1MTAtMDc3NmM4YzgtYTBhZS00NGYxLWE1NTItZGM1YWY2YTc0MjdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA1MDc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhZjFjMjA4YzA0NjQyMjM4ODRhMGFlZjM4NmZmMjYwMjliNDZlZjdhMDBhZGUyZTAyZjliYzU4ZDA5ZDQ0YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FRQicCMQNKSmhuDB7573mmXj-QEnnXRMgpA2CdUD-LQ)
> 
> 原版码率：
> 
> ![image](https://private-user-images.githubusercontent.com/49368462/339630568-a06d220e-fdf9-41d9-a88d-bba12a796f36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNDE5NzUsIm5iZiI6MTcxODM0MTY3NSwicGF0aCI6Ii80OTM2ODQ2Mi8zMzk2MzA1NjgtYTA2ZDIyMGUtZmRmOS00MWQ5LWE4OGQtYmJhMTJhNzk2ZjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA1MDc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwNzYyZWMxYzRiYzYxOWM0MmQ1OWM5MzMwOGI5YWFkMDk5Y2RiZTEwMzFhMDMzZjc4YzRiOWU2NWI3NTQxMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zcYdLjcf0xV1uyG6uOJDXy8dNUtzzstgOp11HjSMDkM)
> 
> 修改版设置：
> 
> ![image](https://private-user-images.githubusercontent.com/49368462/339630626-2b36dd65-a30c-4dd7-8c60-d0194aa9d320.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNDE5NzUsIm5iZiI6MTcxODM0MTY3NSwicGF0aCI6Ii80OTM2ODQ2Mi8zMzk2MzA2MjYtMmIzNmRkNjUtYTMwYy00ZGQ3LThjNjAtZDAxOTRhYTlkMzIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA1MDc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNmE3OTZjYmY1YTQwMjIwYjAzMDc1NTE3OTc0MmZkZmU3YjI5ZDY1YzY3ODRhOGNkODY4ZDc1NGE2ODg2ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3adzOOGfoVfagdljOKCvc5x5qv9FIOdG45FzQnHVqSQ)
> 
> 修改版码率：
> 
> ![image](https://private-user-images.githubusercontent.com/49368462/339630664-3c294825-3831-4eab-8660-1566ea62de5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNDE5NzUsIm5iZiI6MTcxODM0MTY3NSwicGF0aCI6Ii80OTM2ODQ2Mi8zMzk2MzA2NjQtM2MyOTQ4MjUtMzgzMS00ZWFiLTg2NjAtMTU2NmVhNjJkZTViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA1MDc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MjE2N2E0NmVkOTBlZmYzYTkwYmUwNDYxZWNlZjAyOTQ4YmJjMjEyN2Y4NDVmYjgzNjBmYjYwMTgxNjQ1MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4wexN8DcKrp2l4BnpI7UuxcdWrtS9_REGp0Ql6Dm23E)

最新的ipa包确实有点问题。我先回滚到上个版本了。麻烦先下载试一下

**Comment by ChrisKimZHT** [comment]
回滚至 `v9.0.2_ImprovedPointerIdMechanism_20240513` 无问题。

最新版的配置存储似乎有问题，每次启动后配置清空了。然后刚才我重装最新版后，码率就不是卡在 50Mbps 而是卡在 6Mbps 720p 了，估计是卡到默认配置了。

**Comment by TrueZhuangJia** [comment]
> 回滚至 `v9.0.2_ImprovedPointerIdMechanism_20240513` 无问题。
> 
> 最新版的配置存储似乎有问题，每次启动后配置清空了。然后刚才我重装最新版后，码率就不是卡在 50Mbps 而是卡在 6Mbps 720p 了，估计是卡到默认配置了。

是这么回事。 只要先用同一个release页面的20240601就ok，功能也比较完整。我已经把0612先从页面上删掉了。

**Comment by TrueZhuangJia** [comment]
已经配置问题，上传新的IPA了

**Comment by TrueZhuangJia** [comment]
> 已经配置问题，上传新的IPA了

 已经解决配置问题，上传新的IPA了
