### ISSUE TITLE
Add Restart and Sleep Buttons

### ISSUE THREAD

**Issue by KyleZouFE** [TrueZhuangJia/moonlight-ios#40]
Feature Request: Add Restart and Sleep Buttons

Sometimes when using Moonlight, the streaming screen doesn’t load properly (stays black), but the system can still be controlled. In such cases, adding a “Restart” button would make it easier to resolve the issue by restarting the system directly. 
A “Sleep” button could also be helpful for quick sleep mode.

Thank you!

**Comment by TrueZhuangJia** [comment]
# 添加键盘命令 Add Keyboard Command
![image](https://github.com/user-attachments/assets/0ea0f91c-574d-4408-9c92-d5a3e229807a)
<br>Read this instruction:
[How.to.add.keyboard.command.for.moonlight-iOS](https://b23.tv/fgdRJk8)
