### ISSUE TITLE
Auto reverse mouse wheel direction？

### ISSUE THREAD

**Issue by paras-zomby** [TrueZhuangJia/moonlight-ios#41]
**Describe the bug**

I'm not sure if this is a bug or a "feature".
I dislike apple's "nature scrolling" so i disable it in my ipad settings. However, the scrolling direction is reversed in streaming and it restore to nature scrolling. I have tried to enable nature scrolling in my ipad setting again and this time the mouse wheel direction still reversed and scrolls in the normal way.
So i think the moonlight seems to auto reverse scrolling direction? but I want to use normal scrolling way in both streaming and native ipadOS...and I believe a lot people would have the same needs. pls add a button in settings about whether reverse scrolling direction or just disable the auto-reverse func. I think most of people will not like to swich between two ways of scrolling directions frequently...

BTW, I try the original moonlight and it didnt reverse my mouse wheel scrolling direction.

**Comment by TrueZhuangJia** [comment]
TF version has a setting option to reverse wheel direction within moonlight
