### ISSUE TITLE
添加【忽略app手势】开关

### ISSUE THREAD

**Issue by fr1g** [TrueZhuangJia/moonlight-ios#44]
**Is your feature request related to a problem? Please describe.**
有一套快捷键是可以切换焦点窗口所在屏幕的，但是触发命令窗口必然会重定向输入。如果窗口在副屏要推到主屏那还好，但是如果是主屏拽回副屏而手上只有副屏的情况下会导致需要被拽回来的窗口失焦从而无法让快捷键对预期的窗口生效。

**Describe the solution you'd like**
希望在进行app级别手势时不要重定向（加个开关吧！）

**Describe alternatives you've considered**
我觉得让起笔0px的手势都不重定向就行

**Additional context**
我认为这并不是Windows导致的问题，因为同样的手势在原版moonlight不会直接定向到宿主

**Comment by fr1g** [comment]
@TrueZhuangJia 专家哥 看我看我

**Comment by TrueZhuangJia** [comment]
但是触发命令窗口必然会重定向输入

![image](https://github.com/user-attachments/assets/94aedea5-e507-4b15-b1ee-0b8e469dc932)

https://www.bilibili.com/opus/972955228110323730

**Comment by fr1g** [comment]
既然如此，能不能考虑一下上60%是app手势，剩下来下40%作为用户自定义的手势？我这边的问题就是有的窗口我想只在副屏上操作将其拉到副屏这边，如果下40%的手势不重定向并且绑定shift+win+左右，那我就能用手势让窗口在屏幕之间移动了发自我的 iPhone在 2024年12月7日，12:10，TrueZhuanJia ***@***.***> 写道：﻿
但是触发命令窗口必然会重定向输入
image.png (view on web)
https://www.bilibili.com/opus/972955228110323730
