### ISSUE TITLE
能否实现原生触控板鼠标速度输入

### ISSUE THREAD

**Issue by motto1** [TrueZhuangJia/moonlight-ios#6]
在ipad使用键盘夹的触控板时，moonlight无法直接输入ipad原生的鼠标灵敏度。导致在串流是鼠标速度不同于ipad桌面的鼠标速度。我使用微软的rd client没有此问题。请问作者有优化这方面的想法吗。

**Comment by TrueZhuangJia** [comment]
我没有这个设备呢。只有这个mini6 专门用来玩游戏的

**Comment by FishOrBear** [comment]
鼠标的移动速度还是有点奇怪  和其他的远程软件都不一样 例如rd client 向日葵
