### ISSUE TITLE
Add Portrait mode support / 添加竖屏支持

### ISSUE THREAD

**Issue by Minecrafter-Pythoner** [TrueZhuangJia/moonlight-ios#9]
**Is your feature request related to a problem? Please describe.**
Currently the app only supports Landscape (e.g. traditional 16:9 ratio) display support and will automatically spins iOS device to landscape even if the device was formerly in landscape mode with rotation lock on.
目前iOS端app仅支持横屏（即使我将设备调整至竖屏状态并开启旋转锁定，打开moonlight时设备仍然将旋转至横屏）

**Describe the solution you'd like**
Add support to launch the app and use streaming in portrait mode (e.g. 9:16 ratio)
添加竖屏支持，使得iOS设备在竖屏状态下能够对竖屏的windows进行串流

**Describe alternatives you've considered**
None
暂无

**Additional context**
Not yet
暂无

**Comment by Minecrafter-Pythoner** [comment]
P.S. After turning on Portrait mode in App Settings (iPad Pro 11" 2022, iPadOS17.5.1), the app does nothing when I'm streaming and turns the iPad into portrait, which should not be expected behavior?
补充：阅读了Readme和feature list以后在应用设置中启用了竖屏模式，但是开始串流后将iPad旋转至竖屏，应用无反应（即还是像原来那样显示横屏模式的画面）

**Comment by TrueZhuangJia** [comment]
> P.S. After turning on Portrait mode in App Settings (iPad Pro 11" 2022, iPadOS17.5.1), the app does nothing when I'm streaming and turns the iPad into portrait, which should not be expected behavior? 补充：阅读了Readme和feature list以后在应用设置中启用了竖屏模式，但是开始串流后将iPad旋转至竖屏，应用无反应（即还是像原来那样显示横屏模式的画面）

为了避免一些麻烦的bug, 我设定成得先进入app视图才能转屏，主机视图是不能转屏的，转屏后台会自动交换分辨率宽高值，直接开始串流即可。

**Comment by Minecrafter-Pythoner** [comment]
感谢，已解决
